{% set version = "3.0-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatstat.sparse
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatstat.sparse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatstat.sparse/spatstat.sparse_{{ version }}.tar.gz
  sha256: 50bcb27ca6dd5101457922332a952711c2092daadffb360359c6ec16c27fd4be

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-tensor                   # [build_platform != target_platform]
    - r-spatstat.utils           # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-abind                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-abind
    - r-spatstat.utils >=3.0_2
    - r-tensor
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-abind
    - r-spatstat.utils >=3.0_2
    - r-tensor

test:
  commands:
    - $R -e "library('spatstat.sparse')"           # [not win]
    - "\"%R%\" -e \"library('spatstat.sparse')\""  # [win]

about:
  home: http://spatstat.org/
  license: GPL-2.0-or-later
  summary: Defines sparse three-dimensional arrays and supports standard operations on them. The package also includes utility functions for matrix calculations that are common in statistics, such as quadratic forms.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
